"""Politis-Romano stationary bootstrap CI on Sharpe ratio.

Reads a portfolio return time series (one of the timeseries_xs_*.csv
files generated by cross_sectional_smoke.py), computes 1000-replication
stationary bootstrap of the annualized Sharpe ratio, reports 95% CI.

This is the standard rigor for time-series Sharpe inference (handles
serial correlation that vanilla i.i.d. bootstrap would mishandle).

Usage:
    python bootstrap_ci.py --csv timeseries_xs_PatchTST_global_H5_long_short.csv \
        --column portfolio_return_nonoverlap --horizon 5
"""
import argparse
import os
import json
import numpy as np
import pandas as pd


def stationary_bootstrap_indices(n, expected_block, rng):
    """Generate indices via Politis-Romano stationary bootstrap.
    Each block has geometrically-distributed length with mean expected_block."""
    indices = np.zeros(n, dtype=int)
    indices[0] = rng.integers(0, n)
    for i in range(1, n):
        if rng.random() < 1.0 / expected_block:
            indices[i] = rng.integers(0, n)
        else:
            indices[i] = (indices[i - 1] + 1) % n
    return indices


def annualized_sharpe(returns, horizon):
    r = np.asarray(returns, dtype=np.float64)
    r = r[~np.isnan(r)]
    if len(r) < 2:
        return float("nan")
    mu = r.mean()
    sd = r.std(ddof=1)
    if sd < 1e-12:
        return float("nan")
    return mu / sd * np.sqrt(252.0 / horizon)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--csv", required=True)
    p.add_argument("--column", default="portfolio_return_nonoverlap")
    p.add_argument("--horizon", type=int, default=5)
    p.add_argument("--n_boot", type=int, default=1000)
    p.add_argument("--expected_block", type=float, default=5,
                   help="Mean block length in samples; tune for serial correlation.")
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args()

    rng = np.random.default_rng(args.seed)
    df = pd.read_csv(args.csv)
    if args.column not in df.columns:
        raise SystemExit(f"Column {args.column!r} not in {args.csv}. "
                          f"Available: {list(df.columns)}")
    r = df[args.column].dropna().to_numpy()
    print(f"Loaded {len(r)} returns from {args.csv} / column {args.column}", flush=True)

    point = annualized_sharpe(r, args.horizon)
    print(f"Point Sharpe: {point:.4f}", flush=True)

    boot_sharpes = np.zeros(args.n_boot)
    for b in range(args.n_boot):
        idx = stationary_bootstrap_indices(len(r), args.expected_block, rng)
        boot_sharpes[b] = annualized_sharpe(r[idx], args.horizon)

    boot_sharpes = boot_sharpes[~np.isnan(boot_sharpes)]
    lo, mid, hi = np.percentile(boot_sharpes, [2.5, 50, 97.5])
    se = boot_sharpes.std(ddof=1)

    out = {
        "csv": args.csv,
        "column": args.column,
        "n_returns": int(len(r)),
        "horizon": args.horizon,
        "n_boot": int(args.n_boot),
        "expected_block": args.expected_block,
        "point_estimate": float(point),
        "boot_median": float(mid),
        "boot_se": float(se),
        "ci95_lower": float(lo),
        "ci95_upper": float(hi),
    }
    print(f"\n95% bootstrap CI on Sharpe: [{lo:.3f}, {hi:.3f}]  "
          f"(median {mid:.3f}, SE {se:.3f})", flush=True)
    print(f"Point estimate {point:.3f} sits at percentile "
          f"{(boot_sharpes < point).mean()*100:.1f}", flush=True)

    base = os.path.basename(args.csv).replace(".csv", "")
    out_path = os.path.join(os.path.dirname(args.csv), f"bootstrap_{base}.json")
    with open(out_path, "w") as fh:
        json.dump(out, fh, indent=2)
    print(f"\nWrote: {out_path}", flush=True)


if __name__ == "__main__":
    main()
